Cities/Cities/Models/City.cs
using System.ComponentModel.DataAnnotations;

namespace Cities.Models
{
    public class City
    {
        [Display(Name = "City")]
        public string Name { get; set; }
        public string Country { get; set; }
        [DisplayFormat(DataFormatString = "{0:F2}", ApplyFormatInEditMode = true)]
        public int? Population { get; set; }
        public string Notes { get; set; }
    }
}

Cities/Cities/Models/CountryNames.cs
namespace Cities.Models
{
    public enum CountryNames
    {
        UK, USA, France, China
    }
}

Cities/Cities/Models/Repository.cs
using System.Collections.Generic;

namespace Cities.Models
{
    public interface IRepository
    {
        IEnumerable<City> Cities { get; }
        void AddCity(City newCity);
    }

    public class MemoryRepostory : IRepository
    {
        private List<City> cities = new List<City>
        {
            new City { Name = "London", Country = "UK", Population = 8539000},
            new City { Name = "New York", Country = "USA", Population = 8406000 },
            new City { Name = "San Jose", Country = "USA", Population = 998537 },
            new City { Name = "Paris", Country = "France", Population = 2244000 }
        };

        public IEnumerable<City> Cities => cities;

        public void AddCity(City newCity)
        {
            cities.Add(newCity);
        }
    }
}

Cities/Cities/Components/TimeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace Cities.Components
{
    public class TimeViewComponent :ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View(DateTime.Now);
        }
    }
}

Cities/Cities/Controllers/HomeController.cs
using Cities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace Cities.Controllers
{
    public class HomeController : Controller
    {
        private IRepository repository;

        public HomeController(IRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index() => View(repository.Cities);

        public ViewResult Create()
        {
            ViewBag.Countries = new SelectList(repository.Cities.Select(c => c.Country).Distinct());
            return View();
        }

        public ViewResult Edit() 
        {
            ViewBag.Countries = new SelectList(repository.Cities.Select(c=>c.Country).Distinct());
            return View("Create", repository.Cities.First());
        } 

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(City city)
        {
            repository.AddCity(city);
            return RedirectToAction(nameof(Index)); // change to "Index" if doesnt work
        }

    }
}

Cities/Cities/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cities</title>
    <script src="http:ajax.aspmentcdn.com/ajax/jQuery/jquery-3.2.1.min.js"
            asp-fallback-src-include="/lib/jquery/dist/**/*.min.js"
            asp-fallback-src-exclude="**.slim.**"
            asp-fallback-test="window.jQuery"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          asp-fallback-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-fallback-href-exclude="**/*-reboot*,**/*-grid*"
          asp-fallback-test-class="btn"
          asp-fallback-test-property="display"
          asp-fallback-test-value="inline-block"
          rel="stylesheet"/>
</head>
<body class="m-1 p-1">
    <img src="~/images/city.png" asp-append-version="true" />
    <cache expires-after="@TimeSpan.FromSeconds(15)">
        @await Component.InvokeAsync("Time")
    </cache>
    <div title="Cities">@RenderBody()</div>
</body>
</html>


<!--
    <script asp-src-include="/lib/jquery/dist/**/*.min.js"
            asp-src-exclude="**.slim.**,**min.**"
            asp-append-version="true"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <environment names="development">
        <script asp-src-include="/lib/jquery/dist/**/j*.js"
                asp-src-exclude="**.slim.**, **.min.**"></script>
    </environment>
    <environment names="production">
        <script asp-src-include="/lib/jquery/dist/**/*.min.js"
                asp-src-exclude="**.slim.**"></script>
    </environment>



-->